### ISSUE TITLE
Menu navigation

### ISSUE THREAD

**Issue by lbrulet** [EPITECH-Strasbourg-2021/CPP-Arcade-Spec#18]
Hi,

I'm asking myself how does the menu work, is it better to click or to navigate with the keyboard?

**Comment by ratouney** [comment]
Why not both ?

**Comment by ArthurKnoep** [comment]
I guess it depends of the graphical library

**Comment by CedricThomas** [comment]
Keep it clean, keep it simple: Keyboard is the best solution!
