### ISSUE TITLE
Let's vote about PixelBox!

### ISSUE THREAD

**Issue by thibautcornolti** [EPITECH-Strasbourg-2021/CPP-Arcade-Spec#21]
Would you rather do:

- A vector of pixel to handle the pixels of the box
  - Better for the memory
  - Vector must be converted for each resize

- A map with x, y as key and the pixel of the box as value
  - No conversion when resizing and code very easy

PLEASE VOTE AND COMMENT

**Comment by Hirevo** [comment]
My vote:
- [x] Vector
- [ ] Map

We learned how to transition from 2D grid coordinates to its 1D equivalent, so the gain in ease of code isn't that large, in my opinion.
(We could even wrap the operation in a macro if code cleanness is such a concern).

**Comment by thibautcornolti** [comment]
My vote is `Map`. Why? Because there's no thing to do when resizing.
I think it's a bit confusing.
Explaning:

resizing a vector from 3x3 to 5x5 without compute give that result:
```
[a][b][c]
[d][e][ ]
[ ][ ][ ]
```

```
[a][b][c][d][e]
[ ][ ][ ][ ][ ]
[ ][ ][ ][ ][ ]
[ ][ ][ ][ ][ ]
[ ][ ][ ][ ][ ]
```

**Comment by ratouney** [comment]
@thibautcornolti If we have to upscale the grid (3x3 -> 5x5), we should also consider how we'll have to handle downscaling it (5x5 -> 3x3) in which case I don't know which method would be more efficient

**Comment by thibautcornolti** [comment]
@ratouney The Map allows to do not care about the resizing. The couple X,Y doesn't change if the map is of size 3x3 or 5x5.

**Comment by thibautcornolti** [comment]
A Map is too slow, since we'll use a Vector, I close the issue.
