### ISSUE TITLE
Saving Scores

### ISSUE THREAD

**Issue by ratouney** [EPITECH-Strasbourg-2021/CPP-Arcade-Spec#22]
Since our applications are supposed to run between groups, we should also try to save the scores for the different users in the same locations and using the same file format/syntax.

Since we won't try to parse JSON or CSV, we could maybe store them in `~/.arcade/$GAMENAME.scores` such as :

```
Ratouney:420
MemeDude:69
PoloRalphLauren:42
```

(it could also be usefull to keep them ordered from top to bottom, depending on how many entries in the Top3, Top5 or any else the user wants to display)

**Comment by thibautcornolti** [comment]
Not sure about the order but it seems to be a good approach

**Comment by Hirevo** [comment]
I think it should be up to the GameModule implementation to decide.
I don't think the specification should enforce anything about this so I'm closing the issue.
