### ISSUE TITLE
Const GetName Const

### ISSUE THREAD

**Issue by XIIIsan** [EPITECH-Strasbourg-2021/CPP-Arcade-Spec#24]
# PLEASE WRITE YOUR ISSUE IN LEGIBLE ENGLISH (ANY NON-ENGLISH ISSUE WILL BE DISCARDED)

For both library, can we change :
	virtual std::string getName() = 0;
to :
	virtual const std::string getName() const = 0;
?

**Comment by thibautcornolti** [comment]
std::string being a copy, I don't see the point :thinking:

**Comment by Hirevo** [comment]
This has been addressed in #25.
Therefore, I'm closing the issue.
