### ISSUE TITLE
Input Text

### ISSUE THREAD

**Issue by ArthurKnoep** [EPITECH-Strasbourg-2021/CPP-Arcade-Spec#28]
In the subject it's write we need to ask the name of the player in the main menu

How can we handle that with the current implementation of IGraphicLib ?

**Comment by thibautcornolti** [comment]
`pollEvent` ?

**Comment by ArthurKnoep** [comment]
Yep but its cancer

**Comment by rectoria** [comment]
We need a method to set this parameter in IGameLib interface,  or even in the constructor.

**Comment by Hirevo** [comment]
I think this is something we overflew and needs to be addressed.
So should we add a function to the GameModule to set the player in case it needs it ?
