### ISSUE TITLE
Remove loadTextFont

### ISSUE THREAD

**Issue by mqje** [EPITECH-Strasbourg-2021/CPP-Arcade-Spec#29]
I don't understand the goal behind this function: 
```
		virtual void *loadTextFont(std::string path) = 0;
 ```

I never encountered a game that allow us to change a font ingame.

Please enlighten me!

**Comment by mqje** [comment]
same goes for 
```
		virtual void *loadSound(std::string path) = 0;

		virtual void *loadSprite(std::string path) = 0;

```

**Comment by thibautcornolti** [comment]
IN WHICH WORLD THE TETRIS HAS THE SAME FONT AS THE SNAKE????????????????????? 

![](https://cdn.instructables.com/FPN/3PPB/IMM90CZN/FPN3PPBIMM90CZN.LARGE.jpg)

![](https://tetris.com/assets/brand/project-logo.png)

**Comment by ratouney** [comment]
Guillaume said we don't need it... /closed
