### ISSUE TITLE
Text size handling

### ISSUE THREAD

**Issue by thibautcornolti** [EPITECH-Strasbourg-2021/CPP-Arcade-Spec#35]
We are handling the text size with `height` and `width`. How do we convert that in a font size value?

**Comment by Hirevo** [comment]
That's a good question because SFML supports font size, but I think NCurses uses a single font size for the entire window.

**Comment by Hirevo** [comment]
Maybe text rendering could be done by creating a "window" to set a font size and drawing into it.

**Comment by Hirevo** [comment]
In any case, I think `width` and `height` seem inappropriate for text, indeed.

**Comment by thibautcornolti** [comment]
I close this issue since the fix has been merged in #36
