### ISSUE TITLE
Where to Link/Compile our functions for PixelBox, Color&co ?

### ISSUE THREAD

**Issue by ratouney** [EPITECH-Strasbourg-2021/CPP-Arcade-Spec#48]
We have the prototypes for all the general functions that should be common to all libraries but how should we compile them ?

Should we add them to the sources of our main `arcade` binairy ?
Should it be in a `common.so` library that would be required at launch ? (some may have more optimized versions and implementations)

Discuss...

**Comment by Hirevo** [comment]
I think it is up to you (the implementer) to choose.
I personnally compile the Core in the arcade binary.
All the classes like PixelBox, TextBox, Color or Vect compiles to .o files once and are re-used for the core, the games and the graphics libraries.
The common.so route should also be viable.
