### ISSUE TITLE
Coding Style

### ISSUE THREAD

**Issue by ArthurKnoep** [EPITECH-Strasbourg-2021/CPP-Arcade-Spec#49]
In the contructor of `TextBox` we use 5 arguments, which is forbidden by the coding style.

Same for `Color`

**Comment by Hirevo** [comment]
Color is fine actually, it has 4 arguments.
TextBox has that issue and is attempted to be fixed in #54.

**Comment by Hirevo** [comment]
This has been solved now.
Therefore, I'm closing the issue.
