### ISSUE TITLE
How is the PutPixel method supposed to work ?

### ISSUE THREAD

**Issue by ratouney** [EPITECH-Strasbourg-2021/CPP-Arcade-Spec#52]
```
		void putPixel(Vect<size_t> pos, Color col);
		Color getPixel(Vect<size_t> pos) const;

		void putRect(Vect<size_t> pos, Vect<size_t> size, Color col);

		std::vector<Color> &getPixelArray();

	private:
		std::vector<Color> _colorFrame;
```

How are we supposed to store the separate pixels in a vector containing only colors ?
Are we supposed to create our own personnal buffer/map to store at which position we have each color ?

**Comment by Hirevo** [comment]
Yes, that's how we intended to use it.
_colorFrame stores all the pixels for the frame and putPixel changes a Color in this vector.
Same idea with putRect.

**Comment by ratouney** [comment]
So `_colorFrame` is a one-dimensionnal buffer just as we used to work with in CSFML last year ?

**Comment by Hirevo** [comment]
Yes, the formula stays the same:
```C++
const auto index = y * width + x;
```
