### ISSUE TITLE
Percentage

### ISSUE THREAD

**Issue by ArthurKnoep** [EPITECH-Strasbourg-2021/CPP-Arcade-Spec#55]
For the PixelBox, I think the best way to handle it is to use percentage in dimensions.

For example, in sfml the unit are 1920 * 1080 for the creation of the window, in libcaca the unit are 80 * 40 for the creation of the window (it's not pixel, it's character). If we use percentage in the size and the position of the PixelBox, we can handle this sitution without any problem.

**Comment by rectoria** [comment]
Either we use percentages to define the dimensions and offsets, or you can transcribe the usual 1920 * 1080 dimensions according to your library needs.

**Comment by Hirevo** [comment]
Just for clarity, what is to be expressed in percentages:
 - PixelBox::putPixel ?
 - PixelBox::putRect ?
 - IGraphicLib::drawPixelBox ?
 - IGraphicLib::drawText ?

**Comment by Hirevo** [comment]
There's some folks (me included) who considers percentage to not be necessary as the game has access to the window dimensions.

**Comment by thibautcornolti** [comment]
Not sure, just use a decorator / wrapper to handle that issue.
```
void myPutPixel(IGraphicLib *graph, PixelBox &this, Vect<double> perPos, Color col)
{
    auto pixPos = Vect<size_t>(perPos.getX() * graph->getMaxX(), perPos.getY() * graph->getMaxY());
    this->putPixel(pixPos, col)
}
```
