### ISSUE TITLE
Poll event system refactoring

### ISSUE THREAD

**Issue by CedricThomas** [EPITECH-Strasbourg-2021/CPP-Arcade-Spec#57]
We need to rework the event system because the core can't check the list without taking an element out.

**Comment by rectoria** [comment]
The window size unit used by the games and this issue are two topics on which we need to take stock as quickly as possible, as we get closer and closer to the project rendering date.

**Comment by Hirevo** [comment]
My solution to it isn't the one you decided to go for, so please go ahead and propose something, I won't participate in it this time around.

**Comment by CedricThomas** [comment]
It's maybe not the way the more efficient to do that but  about the size, I propose that the game do the resize wwhen he detect a window size changement. In our promotion Luc brulet already did like this and it's look like that's working fine.
