### ISSUE TITLE
Void function IGameLib::update() and IGameLib::applyEvent()

### ISSUE THREAD

**Issue by rectoria** [EPITECH-Strasbourg-2021/CPP-Arcade-Spec#59]
In the current state of these two functions, we have no way of knowing if the player has lost with his previous action or the game cycle. @Hirevo #58. Is it on purpose ?

**Comment by thibautcornolti** [comment]
and we can't make an "exit" button in the game

**Comment by Hirevo** [comment]
The exit button is taken care of by the core. Just like the library switch keys and menu keys.

**Comment by CedricThomas** [comment]
A game over screen in the game and a score registration when the player loose can be the solution. Currently, there is no implementation of a score system in this repository, so we need to think about it.

**Comment by Hirevo** [comment]
Someone ?

**Comment by ratouney** [comment]
We could literally add a `void gameOver()` function that could handle the displaying/loading of scores...

**Comment by Hirevo** [comment]
Which is meant to exit the game following the call to applyEvent or update, true or false ?

**Comment by Hirevo** [comment]
Next time, before calling others for documentation, please document your own things first.
