### ISSUE TITLE
About standardizing DLLoader

### ISSUE THREAD

**Issue by Hirevo** [EPITECH-Strasbourg-2021/CPP-Arcade-Spec#6]
## About standardizing DLLoader

Should we write a common interface for the DLLoader class, or do we implement it on our own ?

**Comment by thibautcornolti** [comment]
Own. But we have to define a standard entry point, which could be `entryPoint` ? :thinking: 
To be compliant with the norm, the entry point would be a static method in `IGameModule` and `IGraphicLib`.

**Comment by ArthurKnoep** [comment]
We cannot put the entryPoint in a class

**Comment by thibautcornolti** [comment]
@ArthurKnoep As we said, what about a static method in each interface to get the instance?

**Comment by ArthurKnoep** [comment]
As I say, we cannot put the entryPoint in a class (I tried and I asked devoille_g). We have to reimplement the bootstrap's method.

I know it break the coding style, but I think faults will be removed

**Comment by thibautcornolti** [comment]
Didn't notice. Good to me

**Comment by ArthurKnoep** [comment]
Just to make everyone agree, we use `entryPoint` as the function name

**Comment by thibautcornolti** [comment]
Let's add the function in a `Arcade.hpp` file if you're ok.
